export const SET_SETTINGS = 'SET_SETTINGS';

export const UPDATE_GENERAL_SETTING = 'UPDATE_GENERAL_SETTING';
export const UPDATE_CONSENT_MODAL_SETTING = 'UPDATE_CONSENT_MODAL_SETTING';
export const UPDATE_SETTINGS_MODAL_SETTING = 'UPDATE_SETTINGS_MODAL_SETTING';

export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';
export const UPDATE_CONSENT_MODAL_LANGUAGE_SETTING = 'UPDATE_CONSENT_MODAL_LANGUAGE_SETTING';
export const UPDATE_SETTINGS_MODAL_LANGUAGE_SETTING = 'UPDATE_SETTINGS_MODAL_LANGUAGE_SETTING';
export const UPDATE_COOKIE_TABLE_HEADERS_LANGUAGE_SETTING = 'UPDATE_COOKIE_TABLE_HEADERS_LANGUAGE_SETTING';
export const UPDATE_SETTINGS_MODAL_BLOCK_LANGUAGE_SETTING = 'UPDATE_SETTINGS_MODAL_BLOCK_LANGUAGE_SETTING';

export const ADD_COOKIE_TABLE_ROW = 'ADD_COOKIE_TABLE_ROW';
export const UPDATE_COOKIE_TABLE_ROW = 'UPDATE_COOKIE_TABLE_ROW';
export const DELETE_COOKIE_TABLE_ROW = 'DELETE_COOKIE_TABLE_ROW';

export const ADD_BLOCKED_SCRIPT = 'ADD_BLOCKED_SCRIPT';
export const UPDATE_BLOCKED_SCRIPT = 'UPDATE_BLOCKED_SCRIPT';
export const DELETE_BLOCKED_SCRIPT = 'DELETE_BLOCKED_SCRIPT';

export const UPDATE_PRIMARY_BUTTON_TEXT = 'UPDATE_PRIMARY_BUTTON_TEXT';
export const UPDATE_PRIMARY_BUTTON_ROLE = 'UPDATE_PRIMARY_BUTTON_ROLE';

export const UPDATE_SECONDARY_BUTTON_TEXT = 'UPDATE_SECONDARY_BUTTON_TEXT';
export const UPDATE_SECONDARY_BUTTON_ROLE = 'UPDATE_SECONDARY_BUTTON_ROLE';

export const UPDATE_COLOR_SETTINGS = 'UPDATE_COLOR_SETTINGS';
export const UPDATE_COLOR_SETTING = 'UPDATE_COLOR_SETTING';

export const UPDATE_GCM_SETTINGS = 'UPDATE_GCM_SETTINGS';
export const UPDATE_GCM_SETTING = 'UPDATE_GCM_SETTING';

export const ADD_GCM_REGION = 'ADD_GCM_REGION';
export const UPDATE_GCM_REGION_SETTING = 'UPDATE_GCM_REGION_SETTING';
export const DELETE_GCM_REGION = 'DELETE_GCM_REGION';

export const UPDATE_PRESSIDIUM_OPTION = 'UPDATE_PRESSIDIUM_OPTION';
export const UPDATE_FONT_SETTING = 'UPDATE_FONT_SETTING';
