export default {
  bg: '#f9faff',
  text: '#112954',
  'btn-primary-bg': '#3859d0',
  'btn-primary-text': '#f9faff',
  'btn-primary-hover-bg': '#1d2e38',
  'btn-primary-hover-text': '#f9faff',
  'btn-secondary-bg': '#dfe7f9',
  'btn-secondary-text': '#112954',
  'btn-secondary-hover-bg': '#c6d1ea',
  'btn-secondary-hover-text': '#112954',
  'toggle-bg-off': '#8fa8d6',
  'toggle-bg-on': '#3859d0',
  'toggle-bg-readonly': '#cbd8f1',
  'toggle-knob-bg': '#fff',
  'toggle-knob-icon-color': '#ecf2fa',
  'cookie-category-block-bg': '#ebeff9',
  'cookie-category-block-bg-hover': '#dbe5f9',
  'section-border': '#f1f3f5',
  'block-text': '#112954',
  'cookie-table-border': '#e1e7f3',
  'overlay-bg': 'rgba(230, 235, 255, .85)',
  'webkit-scrollbar-bg': '#ebeff9',
  'webkit-scrollbar-bg-hover': '#3859d0',
  'btn-floating-bg': '#3859d0',
  'btn-floating-icon': '#f9faff',
  'btn-floating-hover-bg': '#1d2e38',
  'btn-floating-hover-icon': '#f9faff',
};
