export default {
  bg: '#fffcfa',
  text: '#551a11',
  'btn-primary-bg': '#d06139',
  'btn-primary-text': '#fffcfa',
  'btn-primary-hover-bg': '#391d22',
  'btn-primary-hover-text': '#fffcfa',
  'btn-secondary-bg': '#f9e5e1',
  'btn-secondary-text': '#551a11',
  'btn-secondary-hover-bg': '#eacec7',
  'btn-secondary-hover-text': '#551a11',
  'toggle-bg-off': '#d6998f',
  'toggle-bg-on': '#d06139',
  'toggle-bg-readonly': '#f1d0cb',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#faeceb',
  'cookie-category-block-bg': '#f9eeeb',
  'cookie-category-block-bg-hover': '#f9e0dc',
  'section-border': '#f4f0f0',
  'block-text': '#551a11',
  'cookie-table-border': '#f3e4e2',
  'overlay-bg': 'rgba(255, 237, 229, .85)',
  'webkit-scrollbar-bg': '#f9eeeb',
  'webkit-scrollbar-bg-hover': '#d06139',
  'btn-floating-bg': '#d06139',
  'btn-floating-icon': '#fffcfa',
  'btn-floating-hover-bg': '#391d22',
  'btn-floating-hover-icon': '#fffcfa',
};
