export default {
  bg: '#fffafa',
  'primary-color': '#55111a',
  'btn-primary-bg': '#d03939',
  'btn-primary-color': '#fffafa',
  'btn-primary-hover-bg': '#391d29',
  'btn-primary-hover-color': '#fffafa',
  'btn-secondary-bg': '#f9e1e3',
  'btn-secondary-color': '#55111a',
  'btn-secondary-hover-bg': '#eac7ca',
  'btn-secondary-hover-color': '#55111a',
  'toggle-off-bg': '#d68f99',
  'toggle-on-knob-bg': '#d03939',
  'toggle-readonly-bg': '#f1cbd0',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#faebee',
  'cookie-category-block-bg': '#f9ebec',
  'cookie-category-block-hover-bg': '#f9dcdf',
  'separator-border-color': '#f4f0f1',
  'block-text': '#55111a',
  'cookie-table-border': '#f3e2e4',
  'overlay-bg': 'rgba(255, 230, 229, .85)',
  'webkit-scrollbar-bg': '#f9ebec',
  'webkit-scrollbar-bg-hover': '#d03939',
  'btn-floating-bg': '#d03939',
  'btn-floating-icon': '#fffafa',
  'btn-floating-hover-bg': '#391d29',
  'btn-floating-hover-icon': '#fffafa',
};
