export default {
  bg: '#fafffe',
  text: '#115542',
  'btn-primary-bg': '#39d0ba',
  'btn-primary-text': '#fafffe',
  'btn-primary-hover-bg': '#1d392a',
  'btn-primary-hover-text': '#fafffe',
  'btn-secondary-bg': '#e1f9f4',
  'btn-secondary-text': '#115542',
  'btn-secondary-hover-bg': '#c7eae2',
  'btn-secondary-hover-text': '#115542',
  'toggle-bg-off': '#8fd6c2',
  'toggle-bg-on': '#39d0ba',
  'toggle-bg-readonly': '#cbf1e6',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#ebfaf4',
  'cookie-category-block-bg': '#ebf9f6',
  'cookie-category-block-bg-hover': '#dcf9f1',
  'section-border': '#f0f4f3',
  'block-text': '#115542',
  'cookie-table-border': '#e2f3ef',
  'overlay-bg': 'rgba(229, 255, 252, .85)',
  'webkit-scrollbar-bg': '#ebf9f6',
  'webkit-scrollbar-bg-hover': '#39d0ba',
  'btn-floating-bg': '#39d0ba',
  'btn-floating-icon': '#fafffe',
  'btn-floating-hover-bg': '#1d392a',
  'btn-floating-hover-icon': '#fafffe',
};
