export default {
  bg: '#fffafa',
  text: '#55111a',
  'btn-primary-bg': '#d03939',
  'btn-primary-text': '#fffafa',
  'btn-primary-hover-bg': '#391d29',
  'btn-primary-hover-text': '#fffafa',
  'btn-secondary-bg': '#f9e1e3',
  'btn-secondary-text': '#55111a',
  'btn-secondary-hover-bg': '#eac7ca',
  'btn-secondary-hover-text': '#55111a',
  'toggle-bg-off': '#d68f99',
  'toggle-bg-on': '#d03939',
  'toggle-bg-readonly': '#f1cbd0',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#faebee',
  'cookie-category-block-bg': '#f9ebec',
  'cookie-category-block-bg-hover': '#f9dcdf',
  'section-border': '#f4f0f1',
  'block-text': '#55111a',
  'cookie-table-border': '#f3e2e4',
  'overlay-bg': 'rgba(255, 230, 229, .85)',
  'webkit-scrollbar-bg': '#f9ebec',
  'webkit-scrollbar-bg-hover': '#d03939',
  'btn-floating-bg': '#d03939',
  'btn-floating-icon': '#fffafa',
  'btn-floating-hover-bg': '#391d29',
  'btn-floating-hover-icon': '#fffafa',
};
