export default {
  bg: '#fffafd',
  text: '#551140',
  'btn-primary-bg': '#d0398f',
  'btn-primary-text': '#fffafd',
  'btn-primary-hover-bg': '#391d39',
  'btn-primary-hover-text': '#fffafd',
  'btn-secondary-bg': '#f9e1f1',
  'btn-secondary-text': '#551140',
  'btn-secondary-hover-bg': '#eac7de',
  'btn-secondary-hover-text': '#551140',
  'toggle-bg-off': '#d68fc1',
  'toggle-bg-on': '#d0398f',
  'toggle-bg-readonly': '#f1cbe6',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#faebf6',
  'cookie-category-block-bg': '#f9ebf4',
  'cookie-category-block-bg-hover': '#f9dcf0',
  'section-border': '#f4f0f4',
  'block-text': '#551140',
  'cookie-table-border': '#f3e2ee',
  'overlay-bg': 'rgba(255, 229, 244, .85)',
  'webkit-scrollbar-bg': '#f9ebf4',
  'webkit-scrollbar-bg-hover': '#d0398f',
  'btn-floating-bg': '#d0398f',
  'btn-floating-icon': '#fffafd',
  'btn-floating-hover-bg': '#391d39',
  'btn-floating-hover-icon': '#fffafd',
};
