export default {
  bg: '#fafffc',
  text: '#115520',
  'btn-primary-bg': '#39d06e',
  'btn-primary-text': '#fafffc',
  'btn-primary-hover-bg': '#1f391d',
  'btn-primary-hover-text': '#fafffc',
  'btn-secondary-bg': '#e1f9e7',
  'btn-secondary-text': '#115520',
  'btn-secondary-hover-bg': '#c7ead1',
  'btn-secondary-hover-text': '#115520',
  'toggle-bg-off': '#8fd69f',
  'toggle-bg-on': '#39d06e',
  'toggle-bg-readonly': '#cbf1d3',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#ebfaed',
  'cookie-category-block-bg': '#ebf9ef',
  'cookie-category-block-bg-hover': '#dcf9e3',
  'section-border': '#f0f4f0',
  'block-text': '#115520',
  'cookie-table-border': '#e2f3e6',
  'overlay-bg': 'rgba(229, 255, 239, .85)',
  'webkit-scrollbar-bg': '#ebf9ef',
  'webkit-scrollbar-bg-hover': '#39d06e',
  'btn-floating-bg': '#39d06e',
  'btn-floating-icon': '#fafffc',
  'btn-floating-hover-bg': '#1f391d',
  'btn-floating-hover-icon': '#fafffc',
};
