export default {
  bg: '#fafffe',
  'primary-color': '#115542',
  'btn-primary-bg': '#39d0ba',
  'btn-primary-color': '#fafffe',
  'btn-primary-hover-bg': '#1d392a',
  'btn-primary-hover-color': '#fafffe',
  'btn-secondary-bg': '#e1f9f4',
  'btn-secondary-color': '#115542',
  'btn-secondary-hover-bg': '#c7eae2',
  'btn-secondary-hover-color': '#115542',
  'toggle-off-bg': '#8fd6c2',
  'toggle-on-knob-bg': '#39d0ba',
  'toggle-readonly-bg': '#cbf1e6',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#ebfaf4',
  'cookie-category-block-bg': '#ebf9f6',
  'cookie-category-block-hover-bg': '#dcf9f1',
  'separator-border-color': '#f0f4f3',
  'block-text': '#115542',
  'cookie-table-border': '#e2f3ef',
  'overlay-bg': 'rgba(229, 255, 252, .85)',
  'webkit-scrollbar-bg': '#ebf9f6',
  'webkit-scrollbar-bg-hover': '#39d0ba',
  'btn-floating-bg': '#39d0ba',
  'btn-floating-icon': '#fafffe',
  'btn-floating-hover-bg': '#1d392a',
  'btn-floating-hover-icon': '#fafffe',
};
