export default {
  bg: '#fcfaff',
  'primary-color': '#221155',
  'btn-primary-bg': '#7339d0',
  'btn-primary-color': '#fcfaff',
  'btn-primary-hover-bg': '#1d1e39',
  'btn-primary-hover-color': '#fcfaff',
  'btn-secondary-bg': '#e8e1f9',
  'btn-secondary-color': '#221155',
  'btn-secondary-hover-bg': '#d2c7ea',
  'btn-secondary-hover-color': '#221155',
  'toggle-off-bg': '#a18fd6',
  'toggle-on-knob-bg': '#7339d0',
  'toggle-readonly-bg': '#d4cbf1',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#edebfa',
  'cookie-category-block-bg': '#f0ebf9',
  'cookie-category-block-hover-bg': '#e4dcf9',
  'separator-border-color': '#f1f0f4',
  'block-text': '#221155',
  'cookie-table-border': '#e7e2f3',
  'overlay-bg': 'rgba(240, 229, 255, .85)',
  'webkit-scrollbar-bg': '#f0ebf9',
  'webkit-scrollbar-bg-hover': '#7339d0',
  'btn-floating-bg': '#7339d0',
  'btn-floating-icon': '#fcfaff',
  'btn-floating-hover-bg': '#1d1e39',
  'btn-floating-hover-icon': '#fcfaff',
};
