export default {
  bg: '#fffcfa',
  'primary-color': '#551a11',
  'btn-primary-bg': '#d06139',
  'btn-primary-color': '#fffcfa',
  'btn-primary-hover-bg': '#391d22',
  'btn-primary-hover-color': '#fffcfa',
  'btn-secondary-bg': '#f9e5e1',
  'btn-secondary-color': '#551a11',
  'btn-secondary-hover-bg': '#eacec7',
  'btn-secondary-hover-color': '#551a11',
  'toggle-off-bg': '#d6998f',
  'toggle-on-knob-bg': '#d06139',
  'toggle-readonly-bg': '#f1d0cb',
  'toggle-knob-bg': '#ffffff',
  'toggle-knob-icon-color': '#faeceb',
  'cookie-category-block-bg': '#f9eeeb',
  'cookie-category-block-hover-bg': '#f9e0dc',
  'separator-border-color': '#f4f0f0',
  'block-text': '#551a11',
  'cookie-table-border': '#f3e4e2',
  'overlay-bg': 'rgba(255, 237, 229, .85)',
  'webkit-scrollbar-bg': '#f9eeeb',
  'webkit-scrollbar-bg-hover': '#d06139',
  'btn-floating-bg': '#d06139',
  'btn-floating-icon': '#fffcfa',
  'btn-floating-hover-bg': '#391d22',
  'btn-floating-hover-icon': '#fffcfa',
};
